export const MAX_CONCURRENCY = 25;

export const EXCLUDED_ENTITY_TYPES = [
  'DASHBOARD',
  'WORKFLOW',
  'CONDITION',
  'DESTINATION',
  'SECURE_CRED',
  'ENDPOINT',
  'ISSUE',
  'POLICY',
  'MONITOR_DOWNTIME',
  'KEY_TRANSACTION',
  'AWSLAMBDAREGION',
  'AWSUSAGE',
  'PRIVATE_LOCATION',
  'CONTAINER',
  'AWSEVENTSRULEALL',
  'AWSEVENTSRULE',
  'AWSSESREGION',
  'AWSLOGS',
  'AWSTRUSTEDADVISORCHECK',
  'AWSLAMBDAFUNCTIONALIAS',
  'AWSAPIGATEWAYSTAGE',
  'AWSBILLINGSERVICECOST',
  'AWSELASTICBEANSTALKENVIRONMENT',
  'AWSSNSTOPIC',
  'AWSDYNAMODBGLOBALSECONDARYINDEX',
  'AWSVPCNETWORKINTERFACE',
];

export const RECOMMENDATIONS = {
  nrql: 'Query is too broad - add WHERE clause to narrow scope',
  slideWindow: 'Consider removing sliding window',
};
